common:
#  model: "/home/wuhan2021/SG_PR/SG_PR/model/model.pth" #pytorch model
  model: "/home/wuhan2021/SG_PR/SG_PR/20220627/eventsout/Transformer/08/58_best.pth" #pytorch model
#  model: '/home/wuhan2021/SG_PR/SG_PR/model/release_model/3_20/08/model.pth'
  cuda: "0" # cuda id
  batch_size: 128  #batch size
  p_thresh: 3 #distance threshold of positive sample
#  KITTI
  graph_pairs_dir: "/home/wuhan2021/SG_PR/SG_PR/SG_PR_DATA/graphs_sk" #dir contain training or testing data
  pair_list_dir: '/home/wuhan2021/SG_PR/SG_PR/SG_PR_DATA/eval/3_20' #pair list for traning or testing data
  #  KITTI-360  seq_0000
#  graph_pairs_dir: "/media/wuhan2021/ZX1 512G/KITTI-360/0.360-graph" #dir contain training or testing data
#  pair_list_dir: '/media/wuhan2021/ZX1 512G/KITTI-360/6.pairs/pairs_kitti360/neg1/json_pairs'
  #  NCLT  seq_0000
#  graph_pairs_dir: "/media/wuhan2021/ZX1 512G/KITTI-360/0.360-graph" #dir contain training or testing data
#  pair_list_dir: '/media/wuhan2021/ZX1 512G/KITTI-360/6.pairs/pairs_kitti360/neg1/json_pairs'
arch:
  keep_node: 1 #for test
  filters_1: 64
  filters_2: 64
  filters_3: 32
  tensor_neurons: 16
  bottle_neck_neurons: 16
  K: 10 #KNN parameter
train:
  epochs: 50
  train_sequences: ['00','01','02','03','04','05','06','07','09','10']  #list of training sequences
  eval_sequences: ['08'] #list of Validation sequence
  dropout: 0
  learning_rate: 0.001
  weight_decay: 0.0005
  gpu: 0 #gpu id
  logdir: "/home/wuhan2021/SG_PR/SG_PR/20220627/eventsout/08_with_release_model/" #dir to save training results
  node_num: 100 #if node num of a graph is less than node_num, we use zero node to pad it to node_num
eva_batch:
  sequences: ["08",]  #list of sequences to evaluation
  output_path: "/media/wuhan2021/ZX1 512G/SG_PR/results/neg_10"  #dir to save evaluation results
  show: True  #Whether to display the image
eva_pair:
  pair_file: ["./data/0.json","./data/3.json"]
  #pair_file: ["./SG_PR_DATA/graphs_sk/08/000235.json","./SG_PR_DATA/graphs_sk/08/001467.json"]